### PR TITLE
[WIP] Remove dot docker dependency for non-developers

### PR DESCRIPTION
**Pull request by fulldecent**
# Description

This remove the dependency on dot docker for users that simply wish to run or deploy the app without developing it.

## Related Issue

#90

## Motivation and Context

The additional step of installing dot docker requires each user to provide root access on their computer to a script that is not well known.

## How Has This Been Tested

Follow install steps in the README.md to spin up UI.

## Screenshots (if appropriate)

n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

---

# Discussion

Port 8000 is set as the canonical port for the web UI, configurable in docker-compose.yml.

Port 8001 is set as the canonical port for the API, configurable in docker-compose.yml.

# To-do

- [ ] I do not understand the configuration in protractor.conf.js and there is a hard coded port 4200 in there. 
- [ ] Angular was previously configured with `    "start": "ng serve --host=0.0.0.0 --port 80 --publicHost=nightfall",` This is updated in this PR. However it may be better to improve further by removing the `publicHost` parameter altogether.

### CODE REVIEW

**Comment by asishap** [comment]
@fulldecent ,

Failing integration test when we run ./zkp-demo-test. Could you please fix that ?

**Comment by plugged37** [comment]
Can someone help me solve this problem

**Comment by asishap** [comment]
> Can someone help me solve this problem

@plugged37 , @fulldecent

We have fixed the integration test issue in another PR, which created on top of this PR.
could you please take look at this PR #117?

**Comment by fulldecent** [comment]
Closing this in favor of #117

**Pull request closed without merging**
