### PR TITLE
Re-implementing compute witness functionality

### PR DESCRIPTION
**Pull request by willKim19**
# Description

Reimplementing compute witness functionality.

This hasn't fixed the outputs not being printed correctly that we discussed earlier @Westlad but I'm sure this functionality will be necessary later on at any rate.

### CODE REVIEW

**Comment by willKim19** [comment]
@Westlad Also, if you could send me some test args, I could try to get zokrates.js to correctly output larger witnesses.

**Comment by iAmMichaelConnor** [comment]
This PR will need to align with the console logging which is output by `f-token-controller.js` and `nf-token-controller.js`.

```
  console.log(
    'To debug witness computation, use ./zok to run up a zokrates container then paste these arguments into the terminal:',
  );
  console.log(`./zokrates compute-witness -a ${allInputs.join(' ')} -i gm17/ft-mint/out`);
```

The above console log is great, because it gives the user the arguments `${allInputs.join(' ')}`. Since there can be around 50 arguments to `compute-witness`, it would be impractical for a user to generate a valid witness without this console logging providing this witness.

The abstraction of using `docker-compose run zkp npm run computeWitness --` might be more confusing than directly opening a zokrates container and writing the 'proper' zokrates command.

If we do choose to use the `docker-compose run zkp npm run computeWitness --`, we will need to change the above console logging instruction, so that we can quickly copy-pasta the full command (including witness arguments).

**Comment by willKim19** [comment]
The usage would be `npm run computeWitness -- -i <file-name> -a <space-separated-arg-list-in-quotes>` (you wouldn't call the docker-compose directly).

Whether that's easier or more complex than using the zokrates container directly is up to you guys, I can update the PR accordingly or we can close it in favor of the container.

**Comment by Westlad** [comment]
I suggest we close this PR as we probably get more flexibility from running up a zokrates container, which is made easy using the `./zok` script in the root of nightfall

**Comment by willKim19** [comment]
Sounds good to me, I'll close the PR now then.

**Pull request closed without merging**
