### PR TITLE
fix: add linting + small fixes to database

### PR DESCRIPTION
**Pull request by ronbeilinson**
# Description

Added linting to every file in the database folder (where possible). If the fixes caused errors or could not be easily implemented then an /* eslint-disable */ line was added to track the linting errors + warnings. 

## Motivation and Context

These fixes are meant to clean up the code to be more readable and ultimately comply with eslint / prettier coding standards.

## How Has This Been Tested

All code was tested in the app itself.

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by asishap** [comment]
@ronbeilinson 

Seems like you missed to commit the eslint configuration file. Could you please add that ?

**Comment by ronbeilinson** [comment]
@asishap we removed the linting config files at some point during the opensource release so wasn't sure if re-adding it was appropriate. There were other eslint-disable lines in nightfall so assumed it was just to keep track of our internal linting progress. Should we re-add the config files? @Westlad @aj-may

**Comment by asishap** [comment]
> @asishap we removed the linting config files at some point during the opensource release so wasn't sure if re-adding it was appropriate. There were other eslint-disable lines in nightfall so assumed it was just to keep track of our internal linting progress. Should we re-add the config files? @Westlad @aj-may

@ronbeilinson ,

We are planning to extend the linting for each microserivces gradually. So what we can do that add eslint configuration file and .eslintignore files at root level folder. Then in .eslintignore file add references of all folders  except `database` folder and gradually we can remove the folder references from .eslintignore file once linting is completed in each microservices. 

@ronbeilinson @Westlad @aj-may , please share you thoughts.

**Comment by ocgordon** [comment]
Just tested out these changes, and didn't hit any errors creating, transferring, or burning tokens and commitments.

**Comment by ronbeilinson** [comment]
fixed conflicts - tested again with no issues. Please rereview @Westlad @ocgordon @asishap

**Pull request merged**
