### PR TITLE
Feature remove dot docker

### PR DESCRIPTION
**Pull request by asishap**
# Description

This PR fixes the integration test issue in PR #91 
Following are the fixes done in this PR

--Removed virtual-hosts from docker compose files since we are no longer depended on dot docker. 
-- Changed api-gateway endpoint in integration test config file
-- Removed --publicHost attribute from package.json (No longer required)
-- Replaced with new port in protractor config file.(Currently we are not using E2E testing of UI, for future we could use protractor for it).

## Related Issue

#90 

## Motivation and Context

The additional step of installing dot docker requires each user to provide root access on their computer to a script that is not well known.

## How Has This Been Tested

Follow install steps in the README.md to spin up UI.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fulldecent** [comment]
Hi, thanks for sharing. What's the difference with #91?

**Comment by asishap** [comment]
> Hi, thanks for sharing. What's the difference with #91?

Hi @fulldecent 
Following are the changes made in this PR
--Removed virtual-hosts from docker compose files since we are no longer depended on dot docker. 
-- Changed api-gateway endpoint in integration test config file
-- Removed --publicHost attribute from package.json (No longer required)
-- Replaced with new port in protractor config file.(Currently we are not using E2E testing of UI, for future we could use protractor for it).

Please take a look and review this PR.

**Comment by fulldecent** [comment]
I have reviewed this and happy with all the changes.

**Comment by ChaitanyaKonda** [comment]
Reviewed. All tests passed

**Pull request merged**
